---
apiVersion: v1
kind: Namespace
metadata:
  name: $PREFIX-dmz
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: $PREFIX-dmz-gateway
  namespace: $PREFIX-dmz
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      # This will be used to demo Tier1 w/ Bookinfo
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "bookinfo.$PREFIX.cloud.zwickey.net."