---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  displayName: secure-default
  name: secure-default
  organization: tetrate
  tenant: $PREFIX-tetrate
  workspace: $PREFIX-secure-app
spec:
  defaultSecuritySetting:
    authenticationSettings:
      trafficMode: REQUIRED
    authorization:
      mode: WORKSPACE
  displayName: secure-default

