---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: secure-gateway
  group: east-gateway-private
  workspace: $PREFIX-secure-app
  tenant: $PREFIX-demo
  organization: tetrate
spec:
  workloadSelector:
    namespace: $PREFIX-demo-secure
    labels:
      app: $PREFIX-tsb-gateway
  http:
    - name: secure-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: $PREFIX-secure.east.private.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/frontend.$PREFIX-demo-secure.svc.cluster.local"
              port: 8888
    - name: vm-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-vm-certs
      hostname: $PREFIX-vm-secure.east.private.cloud.zwickey.net
      # authentication:
      #   jwt:
      #     audiences:
      #     - backend
      #     issuer: https://keycloak.demo.zwickey.net/auth/realms/tetrate
      #     jwksUri: https://keycloak.demo.zwickey.net/auth/realms/tetrate/protocol/openid-connect/certs
      # authorization:
      #   local:
      #     rules:
      #     - name: backend
      #       from:
      #       - jwt:
      #           iss: https://keycloak.demo.zwickey.net/auth/realms/tetrate
      #           other:
      #             roles: backend
      #           sub: "*"
      #       to:
      #       - methods:
      #         - GET
      #         paths:
      #         - "*"
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/frontend-vm.$PREFIX-demo-secure.svc.cluster.local"
              port: 8080
    - name: secure-backend-internal
      port: 8888
      hostname: $PREFIX-east.secure.private.mesh
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/backend.$PREFIX-demo-secure.svc.cluster.local"
              port: 8888