---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: secure-gateway
  group: east-gateway-private
  workspace: $PREFIX-secure-app
  tenant: $PREFIX-tetrate
  organization: tetrate
spec:
  workloadSelector:
    namespace: $PREFIX-demo-secure
    labels:
      app: $PREFIX-tsb-gateway
  http:
    - name: secure-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: $PREFIX-secure.east.private.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/frontend.$PREFIX-demo-secure.svc.cluster.local"
              port: 8888
    - name: secure-backend-internal
      port: 80
      hostname: $PREFIX-east.secure.private.mesh
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/backend.$PREFIX-demo-secure.svc.cluster.local"
              port: 80
    - name: secure-backend-vm-internal
      port: 80
      hostname: $PREFIX-vm.secure.private.mesh
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/backend-vm.$PREFIX-demo-secure.svc.cluster.local"
              port: 80
    - name: secure-gateway-vm
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-vm-certs
      hostname: $PREFIX-vm-secure.east.private.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/frontend-vm.$PREFIX-demo-secure.svc.cluster.local"
              port: 8080