---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: secure-gateway
  group: west-gateway-private
  workspace: $PREFIX-secure-app
  tenant: $PREFIX-tetrate
  organization: tetrate
spec:
  workloadSelector:
    namespace: $PREFIX-demo-secure
    labels:
      app: $PREFIX-tsb-gateway
  http:
    - name: secure-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: secure.west.private.$PREFIX.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/frontend.$PREFIX-demo-secure.svc.cluster.local"
              port: 8888
    - name: secure-backend-internalk
      port: 80
      hostname: west.secure.$PREFIX.private.mesh
      routing:
        rules:
          - route:
              host: "$PREFIX-demo-secure/backend.$PREFIX-demo-secure.svc.cluster.local"
              port: 80